# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 2448 Poynton Squadron Air Cadets
email: oc.2448@aircadets.org
description: >- # this means to ignore newlines until "baseurl:"
  If you're a fan of aviation, action and adventure, love sports and getting to know people, then you're in the right place!
  2448 Poynton Squadron parades every Monday and Thursday nights at 7pm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.2448atc.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
sqn_number: 2448
sqn_name: Poynton
facebook: 2448atc

# Build settings
markdown: kramdown
permalink: /:title

collections:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
